<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>gff3</string>
        <string>gff</string>
    </array>
    <key>name</key>
    <string>GFF3</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>(##(sequence-region|gff-version))\s+([^\s]+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.definition.meta.GFF3</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.class.meta.GFF3</string>
                </dict>
            </dict>
              <key>name</key>
            <string>comment.line.number-sign.makefile</string>
        </dict>
        <dict>
            <key>match</key>
            <string>#.*</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>comment.definition.meta.GFF3</string>
                </dict>
            </dict>
              <key>name</key>
            <string>comment.line.number-sign.makefile</string>
        </dict>

        <dict>
            <key>match</key>
            <string>(Dbxref|ID|Parent|Derives_from|Name|Alias|Gap|Target|Note|Is_circular|Ontology_term)=([^;]+);</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>support.constant.name.tag.attribute.key.GFF3</string>
                </dict>
                 <key>2</key>
                <dict>
                    <key>name</key>
                    <string>string.attribute.value.GFF3</string>
                </dict>
            </dict>
            <key>name</key>
            <string>comment.line.number-sign.makefile</string>
        </dict>
        <dict>
            <key>match</key>
            <string>([_a-zA-Z]+)=([^;]+);?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.attribute.key.GFF3</string>
                </dict>
                 <key>2</key>
                <dict>
                    <key>name</key>
                    <string>string.attribute.value.GFF3</string>
                </dict>
            </dict>
            <key>name</key>
            <string>comment.line.number-sign.makefile</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\t?[-+.?]</string>
            <key>name</key>
            <string>support.function.reserved.GFF3</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\s+[0-9]+\s[0-9]+\s?</string>
            <key>name</key>
            <string>constant.numeric.GFF3</string>
        </dict>
        <dict>
            <key>match</key>
            <string></string>
            <key>name</key>
            <string>support.function.reserved.GFF3</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>text.GFF3</string>
</dict>
</plist>
